FROM debian

WORKDIR /home/root

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y libncurses5-dev libncursesw5-dev
RUN apt-get install -y xutils-dev
RUN apt-get install -y vim
RUN apt-get install -y default-mysql-client default-libmysqlclient-dev
